# Site settings
title: Northeast Georgia Orchid Society (NEGOS)
description: Join us at 2:00 PM on the 3rd Sunday of each month.  We meet in the Gardenside Room of the State Botanical Garden of Georgia in Athens, GA.
cover: assets/images/coverPhoto.jpg
logo: assets/images/logo.svg
favicon: assets/images/logo.svg # assets/images/favicon.png
baseurl: "/" # the subpath of your site, e.g. /blog/ or / for root
url: "https://negaos.github.io" # the base hostname & protocol for your site
paginate:	5 # The number of posts to show per page on your homepage

# Social
facebook: Northeast-Georgia-Orchid-Society-128617363819993/

#Additional Pages
about: about
contact: mailto:northeastgaorchidsociety@gmail.com
presentations: presentations
privacy-policy: privacy-policy


permalink: /:title


# Google Analytics
analytics_id: ""

# Build settings
markdown: kramdown

kramdown:
  parse_block_html: true

plugins_dir:
  - jekyll-paginate

gems: [jekyll-paginate]

# Settings for rake task
safe: False
lsi: False
username: negaos #github username
repo: negaos #github repository
branch: master #branch
#relative_source: ../negaos/ #source directory
#destination: ../negaos-pages/ #destination directory
#production_url:  https://samanyougarg.com/
#source_url:  https://github.com/samanyougarg/hanuman #source repository url

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
